name: Blockycraft

on:
  pull_request:
    paths:
      - blockycraft/*
      - blockycraft/*/*
      - blockycraft/*/*/*
      - blockycraft/*/*/*/*
      - .github/workflows/main.yml
  push:
    paths:
      - .github/workflows/main.yml

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # - uses: actions/cache@v1.1.0
      #   with:
      #     path: blockycraft/Library
      #     key: blockycraft/Library

      # # - name: Run tests
      # #   uses: webbertakken/unity-test-runner@v1.3
      # #   with:
      # #     unityVersion: 2019.3.14f1

      # - name: Build project
      #   uses: webbertakken/unity-builder@v0.10
      #   with:
      #     projectPath: blockycraft/
      #     unityVersion: 2019.3.14f1
      #     targetPlatform: WebGL

      # - name: Upload to artifacts
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: Build
      #     path: build

      # - name: Package
      #   run: |
      #     ls build/
      #     ls build/WebGL

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        # if: github.ref == 'refs/heads/master'
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: docs/