name: Blockycraft

on:
  pull_request:
    paths:
      - blockycraft/*
      - blockycraft/*/*
      - blockycraft/*/*/*
      - blockycraft/*/*/*/*
      - .github/workflows/main.yml
  push:
    branches:
      - master
    tags:
      - v*

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.3.14f1
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
          - WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v1.1.0
        with:
          path: blockycraft/Library
          key: blockycraft/Library

      # - name: Run tests
      #   uses: webbertakken/unity-test-runner@v1.3
      #   with:
      #     unityVersion: 2019.3.14f1

      - name: Build project
        uses: webbertakken/unity-builder@v1.0
        with:
          projectPath: blockycraft/.
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: blockycraft

      # Upload artifacts if we are working with a release

      - name: Upload to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
          path: build/${{ matrix.targetPlatform }}/

      # We only need to deploy if working with WeBGL

      - name: Copy binaries for distribution
        if: matrix.targetPlatform == 'WebGL'
        run: |
          mkdir -p docs/player
          cp -r build/WebGL/blockycraft/* docs/player

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master' && matrix.targetPlatform == 'WebGL'
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/

      - name: Package artifacts for release
        id: package-artifact
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p artifacts/
          zip -r artifacts/blockycraft-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}.zip build/${{ matrix.targetPlatform }}/
          echo "::set-output name=path::artifacts/blockycraft-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}.zip"

      - name: Create Release
        id: create-release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ steps.package-artifact.outputs.path }}
          asset_name: blockycraft-${{ matrix.targetPlatform }}.zip
          asset_content_type: application/zip